-- ============================================
-- Referral System - Core Tables
-- Migration Date: 2026-01-18
-- Purpose: Enable beta invites (admin) and user referrals
-- ============================================

-- ============================================
-- 1. REFERRAL CODES TABLE
-- ============================================
-- Stores all referral codes (both admin beta invites and user referral links)
CREATE TABLE IF NOT EXISTS public.referral_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('beta_invite', 'user_referral')),
  
  -- Creator information
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_by_type TEXT NOT NULL CHECK (created_by_type IN ('admin', 'user')),
  
  -- Reward configuration
  new_user_reward INTEGER NOT NULL, -- Credits for new user
  referrer_reward INTEGER NOT NULL DEFAULT 0, -- Credits for referrer (0 for beta invites)
  
  -- Usage limits
  max_uses INTEGER, -- NULL = unlimited
  current_uses INTEGER NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ,
  
  -- Status management
  is_active BOOLEAN NOT NULL DEFAULT true,
  deactivated_at TIMESTAMPTZ,
  deactivation_reason TEXT,
  
  -- Metadata
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_referral_codes_code ON public.referral_codes(code);
CREATE INDEX idx_referral_codes_created_by ON public.referral_codes(created_by);
CREATE INDEX idx_referral_codes_type ON public.referral_codes(type);
CREATE INDEX idx_referral_codes_active ON public.referral_codes(is_active) WHERE is_active = true;

-- Comments
COMMENT ON TABLE public.referral_codes IS 'Stores all referral codes (beta invites + user referrals)';
COMMENT ON COLUMN public.referral_codes.type IS 'beta_invite (admin) or user_referral (generated by users)';
COMMENT ON COLUMN public.referral_codes.new_user_reward IS 'Credits awarded to new user on first generation (20 for beta, 5 for referral)';
COMMENT ON COLUMN public.referral_codes.referrer_reward IS 'Credits awarded to referrer (0 for beta, 5 for user referral)';

-- ============================================
-- 2. REFERRAL CLAIMS TABLE
-- ============================================
-- Tracks referral reward claims and their status
CREATE TABLE IF NOT EXISTS public.referral_claims (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  referral_code_id UUID NOT NULL REFERENCES public.referral_codes(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  
  -- New user information
  new_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  new_user_email TEXT NOT NULL,
  new_user_ip TEXT NOT NULL,
  
  -- Referrer information
  referrer_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  
  -- Reward details
  new_user_reward INTEGER NOT NULL,
  referrer_reward INTEGER NOT NULL DEFAULT 0,
  reward_status TEXT NOT NULL DEFAULT 'pending' CHECK (reward_status IN ('pending', 'granted', 'rejected', 'failed')),
  granted_at TIMESTAMPTZ,
  rejection_reason TEXT,
  
  -- Trigger condition (first generation)
  triggered_by_generation_id UUID REFERENCES public.generations(id) ON DELETE SET NULL,
  triggered_at TIMESTAMPTZ,
  
  -- Anti-fraud detection
  fraud_risk_score INTEGER DEFAULT 0,
  fraud_checks JSONB DEFAULT '{}'::jsonb,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_referral_claims_new_user ON public.referral_claims(new_user_id);
CREATE INDEX idx_referral_claims_referrer ON public.referral_claims(referrer_id);
CREATE INDEX idx_referral_claims_code ON public.referral_claims(code);
CREATE INDEX idx_referral_claims_status ON public.referral_claims(reward_status);
CREATE INDEX idx_referral_claims_ip ON public.referral_claims(new_user_ip);
CREATE INDEX idx_referral_claims_email ON public.referral_claims(new_user_email);

-- Comments
COMMENT ON TABLE public.referral_claims IS 'Tracks all referral reward claims and their fulfillment status';
COMMENT ON COLUMN public.referral_claims.reward_status IS 'pending (waiting for first gen) → granted/rejected';
COMMENT ON COLUMN public.referral_claims.fraud_risk_score IS '0-100 score, >70 auto-reject, 40-70 review, <40 auto-approve';

-- ============================================
-- 3. HELPER FUNCTIONS
-- ============================================

-- Function: Generate unique user referral code
CREATE OR REPLACE FUNCTION public.generate_user_referral_code(user_uuid UUID)
RETURNS TEXT AS $$
DECLARE
  user_prefix TEXT;
  random_suffix TEXT;
  new_code TEXT;
  code_exists BOOLEAN;
BEGIN
  -- Get first 2 chars of user ID
  user_prefix := UPPER(SUBSTRING(REPLACE(user_uuid::text, '-', '') FROM 1 FOR 2));
  
  -- Try up to 10 times to generate unique code
  FOR i IN 1..10 LOOP
    -- Generate random 5-char suffix (alphanumeric)
    random_suffix := UPPER(SUBSTRING(MD5(RANDOM()::TEXT) FROM 1 FOR 5));
    new_code := 'REF' || user_prefix || random_suffix;
    
    -- Check if code exists
    SELECT EXISTS(SELECT 1 FROM public.referral_codes WHERE code = new_code) INTO code_exists;
    
    IF NOT code_exists THEN
      RETURN new_code;
    END IF;
  END LOOP;
  
  -- Fallback: use UUID-based code
  RETURN 'REF' || UPPER(SUBSTRING(MD5(user_uuid::text || NOW()::text) FROM 1 FOR 8));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.generate_user_referral_code IS 'Generates unique referral code for user (format: REFXX12345)';

-- ============================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ============================================

ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_claims ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can read their own referral codes
CREATE POLICY "Users can view own referral codes"
  ON public.referral_codes
  FOR SELECT
  USING (auth.uid() = created_by);

-- RLS Policy: Users can view their referral claims (as referrer or new user)
CREATE POLICY "Users can view own referral claims"
  ON public.referral_claims
  FOR SELECT
  USING (auth.uid() = new_user_id OR auth.uid() = referrer_id);

-- RLS Policy: Service role can do everything (for API endpoints)
CREATE POLICY "Service role full access on referral_codes"
  ON public.referral_codes
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access on referral_claims"
  ON public.referral_claims
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ============================================
-- 5. TRIGGER: Auto-update updated_at
-- ============================================

CREATE TRIGGER on_referral_codes_updated
  BEFORE UPDATE ON public.referral_codes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();
